# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/chzyer/readline";
    fetch = {
      type = "git";
      url = "https://github.com/chzyer/readline";
      rev = "2972be24d48e78746da79ba8e24e8b488c9880de";
      sha256 = "104q8dazj8yf6b089jjr82fy9h1g80zyyzvp3g8b44a7d8ngjj6r";
    };
  }
  {
    goPackagePath = "github.com/ianlancetaylor/demangle";
    fetch = {
      type = "git";
      url = "https://github.com/ianlancetaylor/demangle";
      rev = "28f6c0f3b63983aaa99575ca3b693afff7996387";
      sha256 = "0rsq3622gd40f1x1l7caidsxrmzg1993ich2higwd94fqbxs1r83";
    };
  }
]
